BEGIN;

CREATE TABLE IF NOT EXISTS bulk_email_campaigns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_by text NOT NULL,
  filters_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  template_id text NOT NULL,
  subject text NOT NULL,
  preview_text text,
  segment_id text,
  broadcast_id text,
  status text NOT NULL DEFAULT 'draft',
  counts_json jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  scheduled_at timestamptz,
  error_json jsonb
);

CREATE INDEX IF NOT EXISTS bulk_email_campaigns_created_at_idx ON bulk_email_campaigns (created_at DESC);
CREATE INDEX IF NOT EXISTS bulk_email_campaigns_status_idx ON bulk_email_campaigns (status);

CREATE TABLE IF NOT EXISTS bulk_email_recipients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id uuid REFERENCES bulk_email_campaigns(id) ON DELETE CASCADE,
  user_id text,
  email text NOT NULL,
  status text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bulk_email_recipients_campaign_idx ON bulk_email_recipients (campaign_id);
CREATE INDEX IF NOT EXISTS bulk_email_recipients_status_idx ON bulk_email_recipients (status);

COMMIT;
