create table if not exists public.quiz_contendors (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  result_type text not null,
  secondary_type text,
  shadow_type text not null,
  created_at timestamptz not null default now()
);

create index if not exists quiz_contendors_created_at_idx on public.quiz_contendors (created_at desc);
create index if not exists quiz_contendors_email_idx on public.quiz_contendors (email);
